language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - redis-server
env:
  global:
    - REDIS_URL=redis://localhost:6379
    - CC_TEST_REPORTER_ID=f69bb189f348c1d7992d8ed8690d0a2c9c885c1aac45e2f4d48732034592b37b
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  email: false
